### ISSUE TITLE
How to get a single field inside an array of assign?

### ISSUE THREAD

**Issue by LJason77** [fcsonline/drill#102]
I have json: 
```json
{
    "count": 2,
    "rows": [
        {
            "_id": "aaa",
            "name": "AAA"
        },
        {
            "_id": "bbb",
            "name": "BBB"
        }
    ]
}
```

and benchmark.yml: 
```yml
- name: get all
  request:
    url: /get_all
  assign: all
```

I want to get a single id, for example, this kind of: 
```yml
- name: delete
  request:
    url: /del/{{ all.body.rows[0]._id }}
    method: DELETE
```

The above code is not working, what should I do?
