### ISSUE TITLE
Report option doesn't work

### ISSUE THREAD

**Issue by HDBandit** [fcsonline/drill#108]
I am running the following command:

```
drill --benchmark benchmark.yml --stats --no-check-certificate --report loadtesting.report
```

I am getting this error:

```
hread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/g.vico/.cargo/registry/src/github.com-1ecc6299db9ec823/drill-0.7.1/src/main.rs:81:5
```

On the other hand if I remove the option `report` is working well.

The version of drill is: 0.7.1

The benchmark.yml contents is (I think it would fail with any benchmark): 

````
---
base: '{{PROXY_MODEL_URL}}'
iterations: 10000
concurrency: 100
rampup: 2

plan:
  - name: POST predictions Batch size 1
    request:
      url: /current
      method: POST
      body: '{{ item.txn }}'
      headers:
        Content-Type: 'application/json'
    with_items_from_csv:
      file_name: ./transactions.csv
      quote_char: "\'"
```
