### ISSUE TITLE
Question: how to pass a large payload to request body

### ISSUE THREAD

**Issue by picaron** [fcsonline/drill#12]
Hi again!

I am trying to pass a large payload to a PUT request

I trying converting to YAML and putting into the body but when my target API is called, it does not receive any body

here is my scenario:

```
---
threads: 1
base: 'http://localhost:8080'
iterations: 1

plan:
  - name: Update Configuration
    request:
      url: /api/channel/v1/custom/integration/configurations/xyz
      method: PUT
      headers:
        Cookie: "{{ authCookie }}"
        Content-Type: "application/json"
      body:
        domainValidateEndpoint: http://localhost:3000
        crestBaseConfiguration:
          host: http://localhost:3000
          azureHost: http://localhost:3000
          azureManagementHost: http://localhost:3000
          azureResource: http://localhost:3000
          partnerBillingDay: 1
          partnerCenterApiHost: https://api.partnercenter.microsoft.com
          partnerCenterAuthHost: https://login.windows.net
          partnerCenterResource: https://api.partnercenter.microsoft.com
          azureProvisioningDelayInMinutes: 180
          credentialsSetupStep: COMPLETED
          apiSetupStep: COMPLETED
          apiAuthorizationStep: COMPLETED
          configuredByAppDirect: false
          crestConfigurations:
            USA:
              azureConfig:
                clientId: someId
                clientSecret: someSecret
                managementUsername: test@host.com
                managementPassword: someSecret
                grantType: PASSWORD
                encrypted: false
              partnerCenterConfiguration:
                clientId: 6c9f572a-d69a-4e08-b4e5-194696492374
                applicationDomain: dummy.onmicrosoft.com
              resellerCaid: 6c9f572a-d69a-4e08-b4e5-194696492374
              resellerDomain: dummy.onmicrosoft.com
              resellerPurchaseEnabled: true
          cspAzureConfigValid: true
        mosiEnabled: false
        crestEnabled: true
        azureEnabled: true
```
