### ISSUE TITLE
Unable to benchmark IPv6-only localhost

### ISSUE THREAD

**Issue by WGH-** [fcsonline/drill#126]
I have a webserver bound to `[::1]:8080`.

When I use the following plan:
```yaml
---
base: 'http://localhost:8080'
iterations: 1000
concurrency: 10

plan:
- name: aaa
  request:
    url: /aaa.txt
```

All I get is connection refused errors. `curl http://localhost:8080/aaa.txt` works. Judging by `strace`, it doesn't even try to connect to `::1`.

If I use `http://[::1]:8080` as base, it works fine (which is a workaround).
