### ISSUE TITLE
Limit requests when using with_items

### ISSUE THREAD

**Issue by hendric-dev** [fcsonline/drill#131]
I'm using Drill to run different workflows through my API endpoints in order to simulate a user.
Now I would like to use the `with_items` feature to add some randomness to my requests. But instead of doing one request per item, it should only do one request with a random item from the list.
Something along the line:

```yaml
- name: Fetch some users
  request:
    url: /api/users/{{ item }}
  with_one_item_from:
    - 70
    - 73
    - 75
```

I could also imagine it being more generic and allow to choose how many requests are done:

```yaml
- name: Fetch some users
  request:
    url: /api/users/{{ item }}
  times: 1
  shuffle: true
  with_items:
    - 70
    - 73
    - 75
```

Whatever is easier to implement, but the first one would suffice for my use case.

I guess this is not possible already? Sorry if I am overlooking something.
