### ISSUE TITLE
Assign response code for assertions

### ISSUE THREAD

**Issue by leon-puls** [fcsonline/drill#138]
It would be great to be able to assert response codes in assertions, the same way as it is currently done with headers and body.

For example 
```
plan:
  - name: Healthcheck
    request:
      url: /healthcheck
    assign: healthcheck

  - name: Healtchcheck status assertion
    assert:
      key: "healthcheck.response_code"
      value: "200"
```
