### ISSUE TITLE
Tags do not apply to included files

### ISSUE THREAD

**Issue by michaelsproul** [fcsonline/drill#164]
I tried defining a top-level file to combine requests from multiple files like this:

```yaml
# all.yaml
---
base: "http://localhost:3000"
plan:
  - include: ./file1.yaml
  - include: ./file2.yaml
```

```yaml
# file1.yaml
---
- name: is_tagged
  request:
    url: /is_tagged
  tags: [example1]
```

```yaml
# file1.yaml
---
- name: is_not_tagged
  request:
    url: /is_not_tagged
```

I found that tags in `file1.yaml` and `file2.yaml` are _ignored_. Running with `--tags example1` doesn't include the `is_tagged` action from `file1.yaml` (it includes nothing).

I had a play with the code and it's because the tag system operates on the unexpanded YAML and expects tags on top-level items only, here:

https://github.com/fcsonline/drill/blob/f7627bfd005a599638fe6c77963df2c45c00b5dc/src/tags.rs#L29-L55

As a workaround I'm grouping my include files by their tags like this:

```yaml
# all.yaml
plan:
  - include: ./file1.yaml
    tags: [example1]
  - include: ./file2.yaml
```

Figured I would document this here so that this behaviour is known. If we wanted to codify it maybe `tags` on included files could be rejected when loading/parsing? Alternatively, the tag system could be extended to work with recursively included files.

Related: #132
