### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by douglasg14b** [fcsonline/drill#168]
Trying to run this for the first time on Ubuntu 20.04 and it just outputs:

```
./drill --benchmark drillBenchmark.yml
Concurrency 55
Iterations 55
Rampup 0
Base URL [reacted]

Segmentation fault
```

From this config:

```yaml
---
threads: 5
base: '[redacted]'
iterations: 55

plan:
  - name: Send Analytics Data
    request:
      url: /api/v1/analytics/event
      method: POST
      headers:
        Cookie: "...."
        Content-Type: "application/json"
      body: >
        {
          "eventData": {
            "type": "action",
            "name": "ButtonClick_SendVerificationButton",
            "buttonName": "back"
          },
          "context": {
            "scope": "EnterMDNDialog_SendVerificationButton",
            "scopes": ["EnterMDNDialog", "SendVerificationButton"],
            "app": { "appName": "my-app", "appPath": "/my-app", "version": 2 },
            "device": { "os": "Windows", "browser": "Firefox" },
            "identities": { "deviceId": "abcd-1234", "customerId": "abcd-1234" },
            "extra": {
              "isSubscriber": true,
              "verificationType": "MDN",
              "componentType": "BUTTON"
            },
            "meta": {
              "isTest": true,
              "artificial": false
            }
          }
        }

```
