### ISSUE TITLE
`pick` doesn't work for `with_items_range`

### ISSUE THREAD

**Issue by erkannt** [fcsonline/drill#171]
Given this setup I see 1000 requests rather than the expected 10.

```yaml
---

concurrency: 1
base: 'http://localhost:8080'
iterations: 10

plan:
  - name: Post with a random value
    request:
      url: /api/record-evaluation
      method: POST
      body: >
        {
          "foo": "{{ item }}",
        }
      headers: 
        Content-Type: 'application/json'
    with_items_range:
      start: 1
      step: 1
      stop: 100
    shuffle: true
    pick: 1
```

Not very familiar with golang, but searching the code it looks to me like `pick` hasn't been implemented for `with_items_range`?

Happy to try my hand at a PR if that is the case.
