### ISSUE TITLE
{{ index }} not working

### ISSUE THREAD

**Issue by TonyGiorgio** [fcsonline/drill#186]
I see this PR: https://github.com/fcsonline/drill/issues/89

But when I do this very simple repro: 

```
concurrency: 1
iterations: 1

plan:
  - name: Initial assignment for version {{ index }}
    assert:
      key: index
      value: 0

```

I get: 

```
Initial assignment for version {{ index }} index=0?
thread 'main' panicked at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/drill-0.8.2/src/interpolator.rs:44:11:
Unknown 'index' variable!
```

**Comment by fcsonline** [comment]
The root cause: {{ index }} is only defined inside with_items / with_items_range / with_items_from_csv / with_items_from_file requests, where it's the item's position in the list. In your plan there's no such expansion, so index simply doesn't exist — and the strict interpolator panicked with an unhelpful Unknown 'index' variable!.

What you're after is the per-iteration counter, which is already available as {{ iteration }}:

```
plan:
  - name: Initial assignment for version {{ iteration }}
    assert:
      key: iteration
      value: 0
```

I merged #232 to help to catch this misconception.
