### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gudata** [fcsonline/drill#190]
drill 0.8.3

```yaml
---
concurrency: 4
base: 'http://sarah.example.com:49161'
iterations: 50
rampup: 4

plan:
  - name: Support for POST method
    request:
      url: /api/users
      method: POST
      body: foo=bar

```

the output is

∴ RUST_BACKTRACE=full ./drill  -b config.yaml 
Concurrency 4
Iterations 50
Rampup 4
Base URL http://sarah.example.com:49161

Segmentation fault (core dumped)
