### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by daleione** [fcsonline/drill#3]
Threads 4
Iterations 5
Base URL http://baidu.com

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: drill::expandable::include::expand_from_filepath
  10: drill::benchmark::execute
  11: drill::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main

**Comment by fcsonline** [comment]
Can you share you benchmark file, please?

**Comment by fcsonline** [comment]
Ok, got it. You need to describe your plan. If you check the `benchmark` file syntax, you need a `plan` node with all the requests you want to do. Something like this:

```yaml
---
threads: 4
base: 'http://example.com'
iterations: 5

plan:
  - name: Fetch users
    request:
      url: /api/users.json

  - name: Fetch organizations
    request:
      url: /api/organizations
```
