### ISSUE TITLE
assign String from JSON response surrounded by double quotes

### ISSUE THREAD

**Issue by steven89** [fcsonline/drill#35]
When assigning a JSON response, string variable will be surrounded by double quotes and unusable in request url

e.g. assigning to `test` : `{ "id": "abc" }`, using `test.id` for next request as follow `url: /test/{{ test.id }}` will generate the request `http://example.com/test/"abc"` instead of `http://example.com/test/abc`

reproducible example, benchmark file
```yml
---

threads: 1
base: 'https://jsonplaceholder.typicode.com'
iterations: 1
rampup: 0

plan:
  - name: todos1
    request:
      url: /todos/1
    assign: todo
  - name: example
    request:
      url: http://example.com/{{ todo.title }}
```
result
```bash
Threads 1
Iterations 1
Rampup 0
Base URL https://jsonplaceholder.typicode.com

todos1                    https://jsonplaceholder.typicode.com/todos/1 200 OK 246ms
example                   http://example.com/"delectus aut autem" 404 Not Found 345ms
```

(this example doesn't really make sense as title has spaces, but it's to illustrate with publicly available api)

versions:
`rustc 1.35.0 (3c235d560 2019-05-20)`
`drill 0.5.0`
