### ISSUE TITLE
POST-ing a sequence of JSON objects in Drill

### ISSUE THREAD

**Issue by bpr** [fcsonline/drill#42]
The task I'd like to perform with Drill is to have it read a csv file filled with JSON objects representing a transaction (txn) and have it POST to an address with the JSON being the body of the transaction. I've been unsuccessful.

Here is what a simplified yml file looks like

```yaml
---

threads: 1
base: 'http://localhost:8669'
iterations: 1
rampup: 2

plan:
  - name: POST transactions to standalone ledger from CSV
    request:
      url: /submit_transaction
      method: POST
      body: {{ item.txn }}
      headers:
        Content-Type: 'application/json'
    with_items_from_csv:
      file_name: ./log.csv
      quote_char: "\'"
```
and the log.csv file looks like:

```csv
txn
'{"operations": [{"DefineAsset": {"body": {"asset": {"code": {"val":
[114, 255, 1, 164, 16, 58, 220, 131, 26, 36, 233, 7, 83, 132, 2,
250]}, "issuer": {"key":
"RkcRIKYXs_t2CKgxFwLc2AMCKOQP2N0Q3kTuIVIbCII="}, "memo": "",
"confidential_memo": null, "updatable": false, "traceable": false}},
"pubkey": {"key": "RkcRIKYXs_t2CKgxFwLc2AMCKOQP2N0Q3kTuIVIbCII="},
"signature": "b6gc3THsoVFlBlMSUP78IxwPY37c2k-yllJJMtLhc1FW0iko0jSlSOBfjzMbPLdfsE7Dt2ky8ZsxKR9JTMvFAw=="}}],
"credentials": [], "memos": []}'
```

What appears to be happening is that the POST occurs with an empty body, suggesting that the interpolation of the JSON into the body has gone wrong, or I've used the wrong syntax. Any ideas?
