### ISSUE TITLE
Feature Request: Option to disable validation for ssl certificates

### ISSUE THREAD

**Issue by sydev** [fcsonline/drill#5]
It would be nice to make tests to (local) urls with invalid ssl certificates. Maybe an option like this:

```yml
...
plan:
  - name: Get site with invalid ssl certificate
    request:
      validate_ssl: false
      url: /
```

Or for general preventing:

```yml
threads: 4
base: 'https://example.com'
iterations: 5
validate_ssl: false
```

I don´t know if this is currently possible with [hyper](https://hyper.rs/).
