### ISSUE TITLE
Use header from response for the next request

### ISSUE THREAD

**Issue by mario-s** [fcsonline/drill#50]
Hi,

I like this tool a lot.

I have a use case where I have to authenticate with a post request. The successful response contains a token in the header that I have to use in the following request to access more endpoints. The token is dynamic and therefore can not be stored local.

Is there a way to use the token from the header in the response for the header in the next request? Does 'drill' support this?

**Comment by fcsonline** [comment]
Right now we don't support this use case but it would be awesome to include it to `drill`. Right now, we support dynamic headers injecting data from the previous requests like this:

```yaml
---

threads: 1
base: 'http://localhost:3000'
iterations: 1

plan:
  - name: Fetch account headers
    request:
      url: /api/account
    assign: foo

  - name: Dynamic Custom headers
    request:
      url: /api/messages
      headers:
        X-Foo: Bar {{ foo.account_id }}
```

but the `assign` directive stores only the JSON `body` of the request and not headers like you wanted. This is the [piece of code](https://github.com/fcsonline/drill/blob/master/src/actions/request.rs#L246) that does this.

Maybe we can add this to future versions and let users do things like:

```yaml
  - name: Dynamic Custom headers
    request:
      url: /api/messages
      headers:
        X-Foo: Bar {{ foo.headers.token }}
        X-Bar: Bar {{ foo.body.account_id }}
```

But this is a change that is not backwards compatible, so it will be in a major release.
