### ISSUE TITLE
Strip characters like double quotes in 'assign' JSON response values

### ISSUE THREAD

**Issue by patrick-armitage** [fcsonline/drill#57]
Hi guys, not sure if there's a workaround for this current issue.

I have a thread test suite that first posts to an endpoint `/token`, and `assigns` the response value.  I want to get one attribute and pass it in as the token value in subsequent request headers, like this:

```
GET /users/3472742
Headers:
  Bearer as897c98webjk324jkfds9
```

Instead, when I pass in this `assign` response attribute using `{{ response.token }}`, I get hard coded double quotes that break this request:

```
GET /users/3472742
Headers:
  Bearer "as897c98webjk324jkfds9"
```

Is there any way in Drill to strip characters like these from JSON response values?

**Comment by fcsonline** [comment]
Can you attach your benchmark file, please?

**Comment by patrick-armitage** [comment]
Yes, here's an example of the test I'm trying to run, cleansed of any protected info:

```
---
threads: 1
base: 'https://replace-with-base-url'
iterations: 1
rampup: 0

plan:
  - name: Set Accept header
    assign:
      key: header_accept
      value: "application/json"

  - name: Set Content-Type header
    assign:
      key: header_content_type
      value: "application/x-www-form-urlencoded"

  - name: Set Auth header
    assign:
      key: header_auth
      value: "Basic replace-with-auth-token"

  - name: Get token for user {{ item.email }} using password {{ item.plaintext_password }}
    request:
      url: /token
      method: POST
      headers:
        Accept: "{{ header_accept }}"
        Content-Type: "{{ header_content_type }}"
        Authorization: "{{ header_auth }}"
      body: grant_type=password&username={{ item.email }}&password={{ item.plaintext_password }}
    with_items_from_csv: ./fixtures/users.csv
    assign: user

  - name: Get user info
    request:
      url: /users
      method: GET
      headers:
        Accept: "{{ header_accept }}"
        Content-Type: "{{ header_content_type }}"
        Authorization: Bearer {{ user.token }}
```

**Comment by patrick-armitage** [comment]
According to [serde json]() docs:
```
Printing as a plain string without quotation marks involves converting from a JSON string to a Rust string with as_str() or avoiding the use of Value as described in the following section.
```
Perhaps there could be a configurable option to use JSON data `as_str()` Rust strings?  I'm a complete rust n00b so this may not be a helpful idea 😊

**Comment by fcsonline** [comment]
Thanks for this information. I remember a similar bug reported here: https://github.com/fcsonline/drill/issues/35

I'm going to play a bit and release a fix.

**Comment by fcsonline** [comment]
BTW, are you using the last `master` commit or some specific version? I'm saying this because recently the way how to access data from previous requests changed here:

https://github.com/fcsonline/drill/pull/53

**Comment by patrick-armitage** [comment]
Awesome thanks for the help!  I saw there were some reason changes but haven't tested against them, I was testing against `0.5.0`.  I'll verify the behavior on latest master and report back.

**Comment by fcsonline** [comment]
True, I have to sync versions with `crates.io`. It's a pending task I have.

**Comment by patrick-armitage** [comment]
@fcsonline Nice, appears to be working in `0.6.0`:

```
drill-loadtests (master ✘)✹✭ ᐅ drill/target/release/drill -V
drill 0.6.0

drill-loadtests (master ✘)✹✭ ᐅ drill/target/release/drill --benchmark tests/mycode/users.yml
Threads 1
Iterations 1
Rampup 0
Base URL https://my-url.com

Set Accept header         header_accept=application/json
Set Content-Type header   header_content_type=application/x-www-form-urlencoded
Set Auth header           header_auth=Basic 0978sad908sad098asd09s8ad09sa8dsa908dsa098
Get token for user Antonio.Flores@my-url.com using password xxxxxxx https://my-url.com/token 200 OK 1079ms
Get user info using sd98f79ds7fds987fds9f7ds98f7ds9f7ds987fds https://my-url.com/users/9999999/ 200 OK 107ms
```

Here's the example benchmark code I used:
```
  - name: Get token for user {{ item.email }} using password {{ item.plaintext_password }}
    request:
      url: /token
      method: POST
      headers:
        Accept: "{{ header_accept }}"
        Content-Type: "{{ header_content_type }}"
        Authorization: "{{ header_auth }}"
      body: grant_type=password&username={{ item.email }}&password={{ item.plaintext_password }}
    with_items_from_csv: ./fixtures/users.csv
    assign: user

  - name: Get user info using {{ user.body.access_token }}
    request:
      url: /users/111111111/
      method: GET
      headers:
        Accept: "{{ header_accept }}"
        Content-Type: "{{ header_content_type }}"
        Authorization: Bearer {{ user.body.access_token }}
```

**Comment by patrick-armitage** [comment]
Also of interest, to show how this problem originally existed in Serde JSON calls, I created a repo demoing the issue:

https://github.com/patrick-armitage/rust-json-test

**Comment by patrick-armitage** [comment]
Another question I had (which should probably be a separate issue altogether) is dynamically passing in urls with `assign` data, such as:

```

**Comment by fcsonline** [comment]
Great! I'll publish a new release in crates.io during the next days.

About this last comment, technically it is possible. Wrap it with quotes. If not the yaml syntax collides with the interpolations. 


```yaml
  - name: Get user info using {{ user.body.access_token }}
    request:
      url: "https://www.foobar.com/{{ user.body._links.user }}"
```

You can find an example here:

https://github.com/fcsonline/drill/blob/master/example/benchmark.yml#L27
