### ISSUE TITLE
RFC - Rename url keyword from .yml

### ISSUE THREAD

**Issue by jrabello** [fcsonline/drill#68]
There is a minor change that I think it would be quite useful, inside plan object we have a keyword called url:
```
plan:
  - name: plan name
    request:
      url: /users
```
But it's technical name actually is "uri" so, it would make more clear semantically what data to put in this field

Thanks!!
