### ISSUE TITLE
Slicing data and assign to specific thread

### ISSUE THREAD

**Issue by jrabello** [fcsonline/drill#69]
Given the following benchmark file:

```
base: 'myUrl'
threads: 8

plan:
  - name: CRIANDO UM CLIENTE {{ thread }} {{ item.txn }}
    request:
      url: /api/v1/customer/create
      method: POST
      body: '{{ item.txn }}'
      headers:
        Content-Type: 'application/json'
    with_items_from_csv:
      file_name: ../fixtures/cadastro-data.csv
      quote_char: "\'"
```

drill is calling the endpoint with the same row for all threads, is there any way to avoid it?
is it possible to slice the data and assign some range of rows to each thread?
