### ISSUE TITLE
Allow for environment variables to be interpolated with test plans

### ISSUE THREAD

**Issue by Stii** [fcsonline/drill#76]
It would be really neat if we could add environment variables to the yaml plans.

For example you could export some vars:

```bash
$ export BASE_URL='http://localhost:8000'
$ export CONCURRENCY=50
$ export ITERATIONS=100
```

and in the yaml plan make it look at the ENV vars:

```yaml
---

concurrency: {{ $CONCURRENCY }} 
base: {{ $BASE_URL }}
iterations: {{ $ITERATIONS }}

plan:
  - name: homepage
    request:
      url: /
```
