### ISSUE TITLE
Cannot pass simple variable to custom header

### ISSUE THREAD

**Issue by picaron** [fcsonline/drill#8]
Hi 

I am trying the following very basic config:

```
---
threads: 1
base: 'http://localhost:8080'
iterations: 1

plan:
  - name: Setup Auth Token
    assign:
      key: "authCookie"
      value: "JSESSIONID=MYVALUE"
  - name: Get Configuration providers
    request:
      url: /api/some_api
      headers:
        Cookie: {{ authCookie }}
```

But somehow the value authCookie isnt passed to the custom header, I'm getting the following error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I have a series of APIs I want to test but I don't want to have to set the auth cookie on each single request. I want to assign to a variable and have every test use that variable.

This way I can simply set the variable once before running my entire test plan.

**Comment by fcsonline** [comment]
I have investigated why your example was not working and I found a small bug in the regexp matching variables. This is the [commit](https://github.com/fcsonline/drill/commit/2616b2f2f4c65f37fa0c242785ad038ab05f8e6a)

Another problem with your test is how do you declare the `Cookie` header. This is a  successful plan:

```
---
threads: 1
base: 'http://localhost:8080'
iterations: 1

plan:
  - name: Setup Auth Token
    assign:
      key: "authCookie"
      value: "JSESSIONID=MYVALUE"
  - name: Get Configuration providers
    request:
      url: /api/some_api
      headers:
        Cookie: "{{ authCookie }}"
```
The double quotes are important for a proper YAML intepretation.
